group: Validate wheels
steps:
  - label: "MacOS x86_64 Python {{matrix}}"
    job_env: MACOS
    instance_type: macos
    commands:
      - export PYTHON_VERSION={{matrix}}
      - ./.buildkite/release-automation/verify-macos-wheels.sh x86_64
    matrix:
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"

  - label: "MacOS arm64 Python {{matrix}}"
    job_env: MACOS
    instance_type: macos-arm64
    commands:
      - export PYTHON_VERSION={{matrix}}
      - ./.buildkite/release-automation/verify-macos-wheels.sh arm64
    matrix:
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"
